### ISSUE TITLE
Create automated backup

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-docker#116]
Leverage https://github.com/blacklabelops/volumerize

**Comment by JeffVandrewJr** [comment]
This is super cool. Dropbox and Google Drive built in.

**Comment by astupidmoose** [comment]
Yes! Backups are a must. 

I don't think it's important to backup the nodes as they can be resyned, but postgres at a minimum should be automatically backed up.

**Comment by JeffVandrewJr** [comment]
Hey guys,

I've been messing around with various ideas for backups and have some thoughts.

The volumerize tool is cool, but since our users have a variety of different volumes depending on their setup (different lightning instances, plugins, etc). This would require a lot of changes to the `docker-compose-generator` to get right,. Volumizer also starts and stops containers, which is an issue with the `docker-compose` restart policies. [The volumizer docs mention explicitly that this will create conflicts.]

I think it's actually easier to do this with good old fashioned shell scripting. I spent this afternoon coding a very simple backup solution that has two pieces:

1. One new shell script in the `btcpay-docker` directory, called `backup.sh`. This script runs `btcpay-down.sh`, then creates a tarball of `/var/lib/docker` (excluding the bitcoind data dir since it's so huge). Then runs `btcpay-up.sh`. After `btcpay-up.sh`, it hands off the tarball to one of the cloud storage clients

2. A new subdirectory in `btcpay-docker` called `btcpay-backup` would contain clients for Dropbox, Google Drive, Amazon S3, etc. Right now for my testing I have already written the Dropbox client and it works smoothly. All it needs is a Dropbox access token which the user obtains from the Dropbox website. The client reads the access token from an environmental variable. 

The idea would be to have `backup.sh` run via a cron job in the middle of the night. On my testing node, the total downtime required was about 3 minutes. On a "real" instance with lots of transactions, this could of course be higher.

Obviously the tarball would need to be encrypted before sending "real" data to the cloud. I'm open for suggestions on encryption methods that balance security with ease to the user. If `gpg` is used, we somehow need to get the user to either keep his key safe or use the `-c` flag to encrypt via user-selected password (easier for the user, but they'll choose dumb passwords).

I don't have this stuff up on GitHub yet and I'm heading out to dinner now. If the consensus is that this is a decent approach, I'll refine it and make a PR for you all to review. 

I put this all together on a lark, so if the consensus is that it's not the right approach, or that it's a low priority right now, I can certainly bag it! No offense taken on my part. Similarly, if you're planning on incorporating the backup and/or cloud storage ideas directly into the .NET core code instead, no worries and I'll stop working on it.

Tagging @NicolasDorier @Kukks @pavlenex @britttttk @rockstardev

**Comment by NicolasDorier** [comment]
I prefer @JeffVandrewJr solution. It is simpler. Actually in the FastSync save-utxo script, I do quite the same for Bitcoin Core and upload automatically to Azure.

**Comment by Kukks** [comment]
I agree, it sounds better and is simpler.  It also pairs well with the new PR https://github.com/btcpayserver/btcpayserver/pull/708 which allows server admins to integrate btcpay with a number of storage providers.

**Comment by Kukks** [comment]
Maybe we can have a backups UI in btcpay that executes your script, uploads to the integrated storage provider and logs it down. 
![New Mockup 1](https://user-images.githubusercontent.com/1818366/54909169-d9cdcb00-4ee9-11e9-9368-932e51bc48ad.png)

**Comment by JeffVandrewJr** [comment]
@Kukks @NicolasDorier I'll make a PR with what I've got, and if it's useful you guys can hook it into the web UI and make whatever modifications to make it better.

**Comment by JeffVandrewJr** [comment]
I started with Dropbox since it's super easy for non-technical user to grab an account and a code and boom they've got backups.

**Comment by Kukks** [comment]
Does dropbox allow direct file access? I have a feeling it doesn't and will
make my life harder later :D   That said, go for it anyway
ᐧ

**Comment by JeffVandrewJr** [comment]
@Kukks Yep, it allows direct access to the files; it creates a separate BTCPay application folder for them as well. It also has automatic versioning and provides access to the versioning. But the backup script and Dropbox script are totally separate, so you can always use one and ignore the other if you don't want to go the Dropbox direction. What I put together is nothing fancy or special, working on PR now.

**Comment by astupidmoose** [comment]
Awesome! 

Is the dropbox portion optional or forced at the moment? I'd prefer to skip this portion. as I have ethical issues against dropbox lol. I'd much prefer to have a default local backup, with an optional provider set as an additional argument as opposed to mandating one. 

My use case: I see myself as creating backups locally, installing syncthing onto the server, and having the folder sync on my local machine through syncthing. I believe syncthing transmits end-to-end encryption so it should be safe to setup and use out the box. 

Also, for my particular case, I have a few shitcoins I don't want to backup. I don't necessarily want to backup anything past the actual BTCPay database. Is there any reason to backup other directories? Perhaps instead of excluding the BTC data, it simply makes sense to only backup the btcpay database?

**Comment by Kukks** [comment]
@astupidmoose baby steps :P

**Comment by JeffVandrewJr** [comment]
@astupidmoose You'll want to back up your lightning directories especially after channel backups are released.

**Comment by whiteyhat** [comment]
Is this already implemented?

**Comment by NicolasDorier** [comment]
@JeffVandrewJr made a script, but IMHO this is not simple to use if you don't have dropbox. 
You can check what the script does and do your own stuff for backups, but this is still messy :(
