### ISSUE TITLE
When accessing BTCPay server from any URL other than the configured HOST, Nginx will show an error

### ISSUE THREAD

**Issue by woutersamaey** [btcpayserver/btcpayserver-docker#150]
When accessing BTCPay server from any URL other than the configured hostname during setup, Nginx will display an error. This is a known issue and result of the user browsing to the wrong URL.

Just wanted to let everyone know I'm looking into a better solution for this, and want to use this issue for discussion.

A pretty error page explaining that your URL is bad and/or a redirect to the configured hostname would be wonderful instead of the Nginx Bad Gateway error.

I believe we can fix this by dynamically creating an HTML page and putting it in the default Nginx web root + a vhost for the configured host so there is a fallback.

What do you think @NicolasDorier ?

**Comment by Kukks** [comment]
I would actually wish that any domain pointed towards the server would automatically just work and fetch SSL via letsencrypt. My knowledge around nginx is very limited though

**Comment by Kukks** [comment]
BtcPay is already host agnostic since a few months ago, the host specification is only on the docker level( for nginx, lightning)

**Comment by woutersamaey** [comment]
@Kukks you mean to say that you can browse to the IP and get a working BTCPay page? I haven't been able to do that. I mean using HTTP, not HTTPS. HTTPS is always going to be a problem (for now).

About the auto-Let's Encrypt thing, this isn't possible due to the way Let's Encrypt's certbot works.
- Nginx needs to be configured a certain way, opening up a certain URL
- A command needs to run on the command line to request the actual certificate
- Let's Encrypt will validate the domain name by visiting the URL from the first bullet
- You get the cert, now it needs to be added to Nginx config.

This isn't to say there's no future here.

Efforts have been made with Apache using the module mod_md. With mod_md, you only need 1 line in the config and Apache handles everything. This is still experimental and if I remember correctly, it will be bundled with Apache 2.5.

```
MDomain example.org

<VirtualHost *:443>
    ServerName example.org
    DocumentRoot htdocs/a

    SSLEngine on
    # no certificates specification, just the 1 line!
</VirtualHost>
```
This setup will, on server start, contact Let's Encrypt to request a certificate for the domain. If Let's Encrypt can verify the ownership of the domain, the module will retrieve the certificate and its chain, store it in the local file system (see MDStoreDir) and provide it, on next restart, to mod_ssl.

Unfortunately a restart still appears necessary.

More can be found here: https://httpd.apache.org/docs/trunk/mod/mod_md.html

**Comment by NicolasDorier** [comment]
@woutersamaey 

See https://docs.btcpayserver.org/faq-and-common-issues/faq-deployment#btcpay-is-expecting-you-to-access-this-website-from

In a nutshell. BTCPay depends on knowing from which URL the user is accessing it (basically through the Host header and `X-Forwarded-Proto`).

This is because some calls create links which can't always be relative. (A typical example is the `url` field of the invoice, that the merchant must use to redirect the user)

If the user created the invoice via the onion link of btcpay, then the url link will be onion.
---------
That said I think this is unrelated to your complaint, and I understand your complaint and need to fix it myself for my own project.

I think I have a way, will make a PR later today.

**Comment by woutersamaey** [comment]
@NicolasDorier tnx will try it out.
