### ISSUE TITLE
BTCPayServer Repos

### ISSUE THREAD

**Issue by ch4ot1c** [btcpayserver/btcpayserver-docker#21]
How would you feel about `btcpayserver-docker` and `btcpayserver-azure` being merged into a singular repo: `btcpayserver-deploy`? Each platform would have its own directory, in addition to a toplevel `docs/` directory.

That way, `btcpayserver/btcpayserver` can stay as-is (`./build.sh`-driven build), and also have internals-specific docs in a `docs/` dir.

I like the current layout with WooCommerce / Drupal Commerce / Magento / WHMCS / Prestashop as 'plugin' repos; their default configuration(s) & yet another `docs/` can also be in each of these repos. I think they should all have the suffix `-plugin`.

This all could also make the `btcpayserver-docs` repo obsolete... But perhaps it can be reorganized / repurposed.

**Comment by ch4ot1c** [comment]
We could then add to the top of the `btcpayserver/btcpayserver` readme:
'Looking to get started? Visit [github.com/btcpayserver/btcpayserver-deploy]() for the one-click setup.'

**Comment by ch4ot1c** [comment]
`btcpayserver.com` / `btcpayserver/btcpayserver.github.io` isn't live, by the way.

**Comment by NicolasDorier** [comment]
I don't think it should be mixed. Initially `-azure` and `-docker` were merged into one, I split them because when azure is using is not relevant for other environments.

I want to keep `btcpayserver-docs`, it can be seen as an Ebook how to administer BTCPay. I plan to put more stuff into it, this is really a "reference guide".
