### ISSUE TITLE
XMR not syncing

### ISSUE THREAD

**Issue by ShopinBit** [btcpayserver/btcpayserver-docker#385]
I added XMR today as described in the docs with:
`export BTCPAYGEN_CRYPTO3="xmr" `
`. ./btcpay-setup.sh -i`

which worked all fine, also added the wallet, but the node doesn't sync.
Did you already implement the 17.1.1 fix for the hardfork? Or is there a step that I missed?

It just states:
`Synced: False (1 / 0)`

**Comment by Kukks** [comment]
> I added XMR today as described in the docs with:
> `export BTCPAYGEN_CRYPTO3="xmr" `
> `. ./btcpay-setup.sh -i`
> 
> which worked all fine, also added the wallet, but the node doesn't sync.
> Did you already implement the 17.1.1 fix for the hardfork? Or is there a step that I missed?
> 
> It just states:
> `Synced: False (1 / 0)`

17.1.1 is already applied. Please ask in https://chat.btcpayserver.org/btcpayserver/channels/monero for support as Monero is not officially supported by BTCPay

**Comment by NicolasDorier** [comment]
@ShopinBit nothing related to xmr, but if you have a lunanode instance, you can't just activate xmr like this, because this would save XMR data in the main partition which is only 20 GB.

Either you have enough skill to setup another partition.  (I can't guide you, even I would need to look it up)
Either you create a new lunanode instance with XMR from the beginning.
