### ISSUE TITLE
Expand pruning to other crypto nodes

### ISSUE THREAD

**Issue by Kukks** [btcpayserver/btcpayserver-docker#40]
We need to allow pruning to other crypto nodes. Guessing we should add a key to the crypto definition file at this point? We should also duplicate the exisitng btc ones to have fragments starting with `btc-* ` to scale. :)

**Comment by bitcoinshirt** [comment]
This is an important suggestion. We need this to make VPS integrations and 1-click installations easier. Quite specifically, we are stuck in LunaNode deployment exactly because guys have no idea how to prune other coins and what are the requirements for those other coins. By knowing this, we can basically have a very easy way to add shitcoins in a single click, and user would not have to worry about it.
