### ISSUE TITLE
BTCPay generates bitcoin addresses with big gap limit

### ISSUE THREAD

**Issue by Perlover** [btcpayserver/btcpayserver-docker#53]
Hello!

UPDATE: first message here about problem when i didn't understand a root of problem. From second message here i described a problem.

I installed BTCPay and tested Lightning & Bitcoin

After first installation there everything worked fine. I had put "xpub" key, i sent bitcoins and created by BTCPay addresses were valid. I redeemed bitcoins from wallet (Mycelium)
But after i made reconfiguration (https://github.com/btcpayserver/btcpayserver-docker/issues/50) of lighting node. I reconfigured lighting but i didn't change bitcoin settings and not tested addresses again.

Now i see in bitcoin configuration right XPUB key but now it has suffix as -[legacy]
Now i see under xpub field there "No ledger wallet detected. If you own one, use chrome, open the app, and refresh this page" but invoices are created and bitcoin addresses too. But now bitcoin addresses are not valid for my wallet (for xpub).

I sent $132 to invoice created by me for deponstration to people but now i cannot understand what deriviation path was used for this (`1CRacBeizMMwoNZ9BAMTqPRPxihxnuXLCH`). If i will know path i will be able to get private key from xpriv key by (https://iancoleman.io/bip39/) tool. I tried many times other paths but i cannot get same address (`1CRacBeizMMwoNZ9BAMTqPRPxihxnuXLCH`)

What i see there in BTCPay ("Manage Store" -> "General settings" -> Derivation Scheme -> Modify -> DerivationScheme field):

    xpub6CpyqzBEEhGepbeMk5FXsNawsDzgckrpH7oS3AJj4YQdhmQnFJxfPov3j3iRUTrPMF1SBbPvb9evsgUdALjjy7RxaDv1VeM16GeYGtX1fLX-[legacy]

If i press Continue button i didn't see stage of verification of addresses. I see only green message "Derivation scheme for BTC has been modified." in Profile.

I checked this xpub. It's valid without "-[legacy]" suffix and it's BIP32 m/0 path. Last valid address generated by BTCPay there was `19CFM9nQFKLN1TqiK3BxKC9rKmxgyvGkLe` (path is m/0/3). BTCPay should generate address `18nTz4zEVTMpaEFsQitnpqHFdWD3QvGQCF` (now there is transaction but i sent from other wallet). But BTCPay generated as `1CRacBeizMMwoNZ9BAMTqPRPxihxnuXLCH`

And some strange now. In Manage wallet in Transaction tab i see invalid address transaction https://www.smartbit.com.au/tx/688b6db41bab71dca303c871ea616f35986b60bb943660cef89c1aea3439d232 and i see later my other transaction from other wallet to valid address (https://www.smartbit.com.au/tx/e187f74d29d5b36ab3377f03a9fe604b2c162a77757847c4724439063083f053) of same xpub key! So inside BTCPay operates as valid addresses and as invalid ones from one xpub key.

Please help me if possible to understand how can i get private key for `1CRacBeizMMwoNZ9BAMTqPRPxihxnuXLCH`

Thanks

**Comment by Perlover** [comment]
Oohh...!

I guessed to see deeply in paths
I found this address! It has m/0/40 path...
Now i understood why i could not see transaction in my wallet - default the deep is 20 precalculated addresses and Mycelium didn't see this.

I guess that inside BTCPay uses path for bitcoin addresses as amount invoices created before. Many invoices were created in Lightning. May be this main reason. But i see only 29 invoices included bitcoin ones.

But in anyway i think it's some bug - to use same big counter for BIP32 pathes for invoices. Before i created only 3-4 invoices. May be counter was increased after reconfiguration? Or may be path counter to be increased after each lightning invoice too? (i have turned on option only lightning before $100 so many invoices were created only for LN not for BTC)

**Comment by bitcoinshirt** [comment]
I recommend you to use Electrum and [increase gap limit](https://www.youtube.com/watch?v=Fi3pYpzGmmo).

**Comment by Perlover** [comment]
> Also if you resolved the issue as said in the title, please close it.

Ok, but i think it's not good situation for store owner. May be developer will think about same big gap for invoice creation? Why 40 was used for example? I created there only 4-5 bitcoin incvoices and 20-25 lightning invoices. May be 5-10 invoices were created for lightning & bitcoin.

**Comment by bitcoinshirt** [comment]
@Perlover This is a question for your wallet developer and not for BTCPay. Most merchants use Electrum for that very same reason.

Lightning Invoices have nothing to do with this.

**Comment by Perlover** [comment]
@bitcoinshirt gap limit described in BIP44 as 20
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Address_gap_limit
So this question for BTCPay developers - btcpay server used gap limit as 40-4=36 minimum

**Comment by Perlover** [comment]
@bitcoinshirt and detail gap limit of Electrum is 20 too...
http://docs.electrum.org/en/latest/faq.html#what-is-the-gap-limit

**Comment by bitcoinshirt** [comment]
So what is exacly is the issue now? You can change default gap limit in
Electrum, I linked you how above. What does BTCPay have to do with your
wallet? I'm trying to understand what is your point now?

**Comment by Perlover** [comment]
Are you developer?

Problem is easy. Previous invoice was created by BTCPay with path m/0/4. Next with m/0/40
Are your realy don't see problem?
Tomorrow it will create with gap 1200 for example. Problem is that BTCPay doesn't follow BIP standards and bitcoins are not viewed in standard wallets.

**Comment by bitcoinshirt** [comment]
In that case you can keep the issue opened. Your wording was confusing to
understand.

**Comment by NicolasDorier** [comment]
@Perlover the root of the issue is that BTCPay generates a new address for each invoices. This is necessary so we can confidently match a payment to a specific invoice.

Now what happen is that very often people like to create invoices without paying just for testing.
Everytimes this happen, BTCPay takes the next address available. So if 40 invoices are created without getting paid, the first payment will end up being 0/40 which is not detected by wallets.

There is two ways of solving the issue:

1. Use Electrum
2. Use Ledger wallet integration (where BTCPay is the only one tracking your addresses)

I explored some potential solutions to this problem. One solution was to "recycle" address which are unused. But then your store becomes weak to actors generating lot's of addresses to monitor your sales.

Other problem is that a lot of custom are paying late or keep the address for long. Recycling addresses mean that they will end up paying the invoice of somebody else.

**Comment by NicolasDorier** [comment]
Do you mean you set that?

![image](https://user-images.githubusercontent.com/3020646/47066575-890ec380-d221-11e8-9a05-d3b4819d0cad.png)

If this is the case, this should not generate bitcoin addresses for the invoices below 100.

**Comment by NicolasDorier** [comment]
Sorry I mean

![image](https://user-images.githubusercontent.com/3020646/47066626-acd20980-d221-11e8-9472-f93bbb78c30e.png)

**Comment by reablaz** [comment]
Today tought about same issue Perlover is talking about but in little bit different light: For example i have a store with both BTC & LTC - if majority of customers will pay with BTC, i will get generated LTC addresses as well, so if there will be 120 customers who paid with btc before first one who paid with LTC, LTC address will be 120th in my wallet. 

As a workaround is creating different stores for different crypto and handling users choice before BTCPayerServer. 

It may be improved also on servers side, but than, there is need to exclude unused payment type addresses from old orders and re-using them for new invoices. But there may be a problem, when it comes to parallel invoice generation i think..

**Comment by NicolasDorier** [comment]
re-using them is tricky.
Not only it happens quite often that the user copy paste his address somewhere and pay days later, but you open yourself to hacker generating lot's of invoices to know all your addresses, and thus your future payments.

**Comment by NicolasDorier** [comment]
That said, I think @Kukks wanted to improve the create invoice API so one could limit the type of payment accepted.

**Comment by Kukks** [comment]
I think this should be moved to btcpayserver repo

**Comment by NicolasDorier** [comment]
I am closing this now. It works for Bitcoin. Will work for Litecoin when they release 0.17

**Comment by enriquepiatti** [comment]
What is the status of this? should we manage the gap limit manually with BTCPay?     


> re-using them is tricky.
> Not only it happens quite often that the user copy paste his address somewhere and pay days later, but you open yourself to hacker generating lot's of invoices to know all your addresses, and thus your future payments.


But then a hacker could generate a lot of invoices just to bypass our gap limit and then nobody else can buy in our site?

**Comment by NicolasDorier** [comment]
@enriquepiatti BTCpay always know about what is paid, because it is the one generating addresses.

The problem of gap limit comes in either if:
1. You manage your wallet from another wallet software
2. You restore old wallet.

There is no way to fix the situation of gap limit without `scantxoutset` (which is supported by litecoin now).

**Comment by enriquepiatti** [comment]
Thanks @NicolasDorier, so we have two options?    
1) Use BTCPay not only as payment processor but also as wallet (possible security risk because our wallet will be online?)
2) Use some wallet compatible with big gaps? (Electrum? any other?)

**Comment by NicolasDorier** [comment]
1. No security risk, as BTCPay never have your private key. Just use the Ledger Nano S integration.
2. Electrum is OK, but my personal advice if you are ok with bech32 addresses and no shitcoin is Wasabi wallet. Just use the hardware wallet integration and import the zpub inside btcpay.

**Comment by enriquepiatti** [comment]
But what do you mean with "manage your wallet from another wallet software"? we are always managing the wallet from another wallet software right? I feel I'm missing something.    
I mean our wallet is not in BTCPay, only the public key to generate addresses, but to send money we always manage the wallet from outside.    
So my question is what could be the problem with gap limit?, I've read that some funds could be inaccessible.   
I think this is a really big problem of the current BTC implementation, is not prepared at all for ecommerce, people going to checkout and not paying is very common, 20 and even 100 is a really low number for that limit. And attackers could do just that to block the payment system with a big gap.    
I guess the external gateways (bitpay, coinbase, etc) are managing this somehow, so I neet to be sure there is no risk to loose the payments and funds in my wallet just because a gap limit.    
Are Electrum, Wasabi and Ledger Nano S working for any gap?
