### ISSUE TITLE
Additional fragment can't replace image name

### ISSUE THREAD

**Issue by sigHash** [btcpayserver/btcpayserver-docker#66]
```
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="mybtcpayserver.custom.yml"
```

mybtcpayserver.custom.yml 
```
version: "3"

services:
  btcpayserver:
    image: xxxxx.dkr.ecr.xx-xxxx-x.amazonaws.com/btcpayserver:latest

```

```
. ./btcpay-setup.sh -i
```

output:

```
Unhandled Exception: System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DockerGenerator.DockerComposeDefinition.<>c.<Merge>b__16_2(IGrouping`2 group) in /source/DockerComposeDefinition.cs:line 97
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at DockerGenerator.DockerComposeDefinition.Build() in /source/DockerComposeDefinition.cs:line 82
   at DockerGenerator.Program.Main(String[] args) in /source/Program.cs:line 26
```

**Comment by NicolasDorier** [comment]
You can't do this. Instead use `export BTCPAY_IMAGE=xxxxx.dkr.ecr.xx-xxxx-x.amazonaws.com/btcpayserver:latest` and run the setup

**Comment by AfolabiOlaoluwa** [comment]
@NicolasDorier Thank you for your last answer to this question. I am currently trying to use a custom docker image on my aws server and this answer appeared to be the way, but I am confused about credentials I will put in the `xxxxx.dkr.ecr.xx-xxxx-x.` part of that answer. I will be glad if you can school me. 

Thanks in advance.

**Comment by AfolabiOlaoluwa** [comment]
Thank you @dennisreimann, that was helpful. However, it did not work. The error I am getting when I run `. .btcpay-setup.sh -i` is `ERROR: no such image: https:/XXXXXXXXXXXX.dkr.ecr.XX-XXXX-X.amazonaws.com/my_docker_image: invalid reference format`.

Kindly pay attention to  `https:/`. There was nothing I did that could puts the second backward slash there. Something removes the second backward slash from `https://`

I also went ahead to hard code BTCPAY-IMAGE on the `btcpay-setup.sh` file, but once I run it, it removes the second slash and I feel that is where the problem is. 

Can you lead me to where the problem is hopefully I can make a PR to this?

**Comment by Kukks** [comment]
Try `////`

**Comment by AfolabiOlaoluwa** [comment]
> Try `////`

I have done that before, it threw away all the backward slashes leaving just only one when the sh file runs.
