### ISSUE TITLE
BTCPAY_ANNOUNCEABLE_HOST is reset to BTCPAY_HOST on upgrades

### ISSUE THREAD

**Issue by benjaminchodroff** [btcpayserver/btcpayserver-docker#845]
When running an upgrade using `. btcpay-setup.sh -i` I am finding that the environment variable BTCPAY_ANNOUNCEABLE_HOST (allowing me to specify a different subdomain for the core lightning server) that I have specified is being overwritten back to BTCPAY_HOST.

This appears to be a logic bug in helpers.sh on line 65. I have fixed it by commenting out defaulting to clearing the variable, and amending the logic to check if BTCPAY_ANNOUNCEABLE_HOST is not set, only then set it to the default BTCPAY_HOST (otherwise, don't overwrite it)

```
    #BTCPAY_ANNOUNCEABLE_HOST=""
    if [[ ! "$BTCPAY_ANNOUNCEABLE_HOST" ]] && [[ "$BTCPAY_HOST" != *.local ]] && [[ "$BTCPAY_HOST" != *.lan ]]; then
        BTCPAY_ANNOUNCEABLE_HOST="$BTCPAY_HOST"
    fi
```

I'm happy to submit a pull request if others agree this is correct way to handle it?

**Comment by NicolasDorier** [comment]
@benjaminchodroff the problem is that `BTCPAY_ANNOUNCEABLE_HOST` isn't meant to be set by users, this is internal.

With your fix, if you change your `BTCPAY_HOST`, this won't change the `BTCPAY_ANNOUNCEABLE_HOST`, and we don't want that.

A better fix I believe is to add a new configuration `BTCPAY_LIGHTNING_HOST`, and set the `BTCPAY_ANNOUNCEABLE_HOST` to it if it is set. On it.

**Comment by benjaminchodroff** [comment]
Was not aware that the BTCPAY_ANNOUNCEABLE_HOST wasn't meant to be set - thanks for the explanation.

I'll go ahead and make a BTCPAY_LIGHTNING_HOST in my local configuration (it's probably an edge case others don't normally use) and use this to adjust the BTCPAY_ANNOUNCEABLE_HOST. Thanks again.

**Comment by NicolasDorier** [comment]
merged it
